feat(*): Initial commit
deis/example-grpc-client pull request #1
Opened 2016-10-31 19:41 UTC by kmala

2016-10-31 19:57 UTC, bacongobbler commented on README.md
> +This guide will walk you through deploying a Go [grpc][grpc] client on [Deis Workflow][]. The client also runs a Go http server which is routable outside of the cluster and proxies the user requests
Can you add more explicit docs here saying that to use this demo, you need to deploy example-grpc-server first, then point SERVER_NAME to that app? I don't think a link is sufficient IMO

2016-10-31 19:58 UTC, bacongobbler commented on README.md
> +This guide will walk you through deploying a Go [grpc][grpc] client on [Deis Workflow][]. The client also runs a Go http server which is routable outside of the cluster and proxies the user requests
Just a link to the grpc server README would suffice since that README contains the demo.

2016-10-31 20:21 UTC, vdice commented on README.md
> +This guide will walk you through deploying a Go [grpc][grpc] client on [Deis Workflow][]. The client also runs a Go http server which is routable outside of the cluster and proxies the user requests
Typo: Assuming `The server Go Server...` is intended to be `The Go server...`

2016-10-31 20:22 UTC, vdice commented on README.md
> +This guide will walk you through deploying a Go [grpc][grpc] client on [Deis Workflow][]. The client also runs a Go http server which is routable outside of the cluster and proxies the user requests
Also `needs to be send` -> `needs to be sent`

2016-10-31 23:12 UTC, vdice commented
Besides typos, code LGTM and tested w/ associated example-grpc-server

2016-10-31 23:21 UTC, vdice commented on main.go
> +// poweredByHandler writes a response by qurying the grpc server.
s/qurying/querying

2016-11-01 23:08 UTC, mboersma commented on glide.lock
> +- name: github.com/kmala/example-grpc-server
This package and the SHA will need to change once example-grpc-server is merged.

2016-11-01 23:09 UTC, mboersma approved these changes
Tested with example-grpc-server. Looks great, with the caveat I noted below about changing the SHA and package name.

2016-11-02 15:25 UTC, bacongobbler requested changes

2016-11-02 15:25 UTC, bacongobbler commented on main.go
> +		log.Println("Server not configured")
can you add here "Server not configured. Please set $SERVER_NAME"

2016-11-02 15:25 UTC, bacongobbler commented on main.go
> +	address := fmt.Sprintf("%s.%s.svc.cluster.local:80", server, server)
is it completely necessary to use the full DNS name along with port 80? I thought `name.name` could be used in most cases. At the very least the `:80` is a bit overkill for this case :)

2016-11-02 16:41 UTC, kmala commented on main.go
> +	address := fmt.Sprintf("%s.%s.svc.cluster.local:80", server, server)
changed to use just `name.name`, thought using the full dns name will provide more clarity but port is needed for the grpc to use.

2016-11-03 15:00 UTC, bacongobbler approved these changes

2016-11-03 15:04 UTC, merged